version: '3'

services:
  nginx:
    image: nginx:1.17
    ports:
      - 8003:8003
      - 8004:8004
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/var/www

